import { useState, useCallback } from "react";

interface Figure {
  id: string;
  paper: string;
  paperLabel: string;
  figNum: string;
  title: string;
  description: string;
  file: string;
  type: "svg" | "png";
  status: string;
  statusColor: string;
  interactive?: string;
}

const FIGURES: Figure[] = [
  // ── Paper A — Core Methods ───────────────────────────────────────────────
  {
    id: "a-fig1",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 1",
    title: "AR(2) Method Schematic",
    description: "The full pipeline from raw gene expression time series to eigenvalue modulus |λ|. Shows AR(2) fitting, characteristic polynomial, eigenvalue extraction, and the stationarity triangle. The core methodological illustration of the entire framework.",
    file: "/figures/paper-a/Figure_1_Method_Schematic.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/dashboard",
  },
  {
    id: "a-fig2",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 2",
    title: "Eigenvalue Hierarchy — Clock > Target > Background",
    description: "The central finding of Paper A. Clock genes sit at higher |λ| than clock-controlled targets, which sit above the genome background. Shown across 22 datasets and 12 tissues. The hierarchy is consistent and statistically significant at every level.",
    file: "/figures/paper-a/Figure_2_Eigenvalue_Hierarchy.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/dashboard",
  },
  {
    id: "a-fig3",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 3",
    title: "ODE Model Validation",
    description: "AR(2) eigenvalue estimates compared against analytical eigenvalues from 6 canonical ODE models (Goodwin, van der Pol, repressilator, and others). Confirms the method recovers known eigenvalues from simulated time series generated by models with exact solutions.",
    file: "/figures/paper-a/Figure_3_ODE_Validation.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/model-zoo",
  },
  {
    id: "a-fig4",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 4",
    title: "Robustness Suite — 12 Stress Tests",
    description: "12-panel robustness analysis varying sampling rate, noise level, time series length, and missing data fraction. The clock-target |λ| hierarchy persists across all perturbations tested, establishing the method's reliability under realistic biological data conditions.",
    file: "/figures/paper-a/Figure_4_Robustness_Suite.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/supplementary-analyses",
  },
  {
    id: "a-fig5",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 5",
    title: "Bmal1-KO Causal Test",
    description: "Clock vs target |λ| in WT vs Bmal1-KO mouse liver (GSE70499). The KO narrows the hierarchy gap by 57% (WT +0.116 → KO +0.050), confirming that the clock programme drives the elevated persistence of clock genes. A direct causal perturbation test.",
    file: "/figures/paper-a/Figure_5_Bmal1_Knockout.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
  },
  {
    id: "a-fig6",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 6",
    title: "Literature Falsification Test",
    description: "Bidirectional test against 59 genes with known circadian roles from published literature. 98.3% show |λ| above the background median — a ~3.9-fold enrichment over chance (enrichment above a broad threshold, not unique identification). Shows both confirmation and the framework's falsifiability.",
    file: "/figures/paper-a/Figure_6_Literature_Falsification.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/literature-validation",
  },
  {
    id: "a-fig7",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 7",
    title: "Bias Audit — Non-Circadian Datasets",
    description: "The most important falsification figure. AR(2) applied to non-circadian datasets (yeast metabolic cycle, bacterial cell cycle, LPS-stimulated NF-κB). No clock-target hierarchy is detected, confirming the method is not a universal feature of any time series and is specific to circadian data.",
    file: "/figures/paper-a/Figure_7_Bias_NonCircadian.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
  },
  {
    id: "a-fig8",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 8",
    title: "Monte Carlo Simulation Study",
    description: "Systematic bias and RMSE analysis for the |λ| estimator across 10,000 simulations per condition. Varies noise, sampling rate, and series length. Shows the estimator is unbiased in the circadian-realistic parameter range and has well-calibrated confidence intervals.",
    file: "/figures/paper-a/Figure_8_Monte_Carlo.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/framework-benchmarks",
  },
  {
    id: "a-fig9",
    paper: "paper-a",
    paperLabel: "Paper A",
    figNum: "Figure 9",
    title: "Head-to-Head: AR(2) vs Cosinor vs JTK_CYCLE",
    description: "Direct comparison of AR(2) temporal persistence against cosinor amplitude and JTK_CYCLE rhythmicity scores on the same datasets. The three metrics are orthogonal — high |λ| genes are not preferentially rhythmic by the other methods. Persistence and rhythmicity measure different things.",
    file: "/figures/paper-a/Figure_9_Head_to_Head.png",
    type: "png",
    status: "Under review · Chronobiology International",
    statusColor: "bg-emerald-500/20 text-emerald-300 border-emerald-600/40",
    interactive: "/framework-benchmarks",
  },

  // ── Paper E — Phase-Gated PAR(2) ─────────────────────────────────────────
  {
    id: "e-fig1",
    paper: "paper-e",
    paperLabel: "Paper E",
    figNum: "Figure 1",
    title: "Phase-Gated PAR(2) Schematic",
    description: "Extended PAR(2) model architecture adding phase-dependent coupling between clock and target genes. Illustrates how the coupling coefficient between a clock driver and a downstream target varies as a function of circadian phase, creating tissue-specific gating windows.",
    file: "/figures/paper-e-main/Figure_1_PAR2_Schematic.png",
    type: "png",
    status: "Revision v4.0 · Journal of Biological Rhythms",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "e-fig2",
    paper: "paper-e",
    paperLabel: "Paper E",
    figNum: "Figure 2",
    title: "Cross-Tissue Clock-Target Coupling",
    description: "Phase-gated coupling across 28,138 clock-target pairs in liver, heart, cerebellum, and intestinal organoids. Wee1 emerges as the dominant coupling hub in liver (coupling in 10/12 tissues). Tead1/YAP1 in heart, Cdk1 in cerebellum. Each tissue has a distinct gating architecture.",
    file: "/figures/paper-e-main/Figure_2_Cross_Tissue_Coupling.png",
    type: "png",
    status: "Revision v4.0 · Journal of Biological Rhythms",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/phase-gating",
  },
  {
    id: "e-fig3",
    paper: "paper-e",
    paperLabel: "Paper E",
    figNum: "Figure 3",
    title: "Organoid Perturbation — Phase-Gating Collapse",
    description: "Phase-gated coupling analysis in the four GSE157357 organoid genotypes (WT, BmalKO, ApcKO, DblKO). Shows how ApcKO disrupts clock→E2F gating while the clock programme itself is maintained. DblKO restores partial gating. Separates the coupling loss from the persistence change.",
    file: "/figures/paper-e-main/Figure_3_Organoid_Perturbation.png",
    type: "png",
    status: "Revision v4.0 · Journal of Biological Rhythms",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/gse157357-analysis",
  },
  {
    id: "e-figs5",
    paper: "paper-e",
    paperLabel: "Paper E",
    figNum: "Figure S5",
    title: "PAR(2) Benchmark — ODE Simulation",
    description: "Monte Carlo simulation comparing AR(2) eigenvalue recovery against cosinor and JTK_CYCLE across varying noise levels and sampling rates. Demonstrates superior recovery of persistence structure under circadian-realistic conditions.",
    file: "/figures/paper-e/Supplementary_Fig_S5_PAR2_Benchmark.png",
    type: "png",
    status: "Revision v4.0 · Journal of Biological Rhythms",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },

  // ── Paper F — Half-Life Independence ─────────────────────────────────────
  {
    id: "f-fig1",
    paper: "paper-f",
    paperLabel: "Paper F",
    figNum: "Figure 1",
    title: "mRNA Half-Life vs |λ| — No Detectable Correlation",
    description: "Scatter of |λ| against published mRNA half-life estimates across ~23,000 genes. Spearman ρ = 0.012. The key falsification figure for an obvious confounder hypothesis: if |λ| just measured mRNA stability, half-life would predict it. It does not.",
    file: "/figures/paper-f/Figure1_Halflife_Independence.png",
    type: "png",
    status: "Draft · Genome Biology",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/halflife-replication",
  },
  {
    id: "f-fig2",
    paper: "paper-f",
    paperLabel: "Paper F",
    figNum: "Figure 2",
    title: "IFIT1 Case Study — Short Half-Life, High |λ|",
    description: "Interferon-induced IFIT1 has one of the shortest mRNA half-lives in the transcriptome (~30 min) yet shows high eigenvalue modulus. Illustrates the conceptual point: |λ| measures how the system generates persistent dynamics, not how long any given molecule survives.",
    file: "/figures/paper-f/Figure2_IFIT1_CaseStudy.png",
    type: "png",
    status: "Draft · Genome Biology",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "f-fig3",
    paper: "paper-f",
    paperLabel: "Paper F",
    figNum: "Figure 3",
    title: "Cross-Dataset Half-Life Independence Replication",
    description: "Half-life independence replicated across 5 independent non-circadian datasets — yeast, bacterial, and two human cell line datasets. Confirms the ρ ≈ 0 result is not dataset-specific. The limitation noted in Paper F: no genome-wide mouse liver half-life dataset currently exists.",
    file: "/figures/paper-f/Figure3_CrossDataset_Validation.png",
    type: "png",
    status: "Draft · Genome Biology",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "f-fig4",
    paper: "paper-f",
    paperLabel: "Paper F",
    figNum: "Figure 4",
    title: "Bias Audit — Expression Level Confounding",
    description: "Tests whether |λ| correlates with mean expression level (a potential technical confounder — high-expression genes might show artificially high AR estimates). Permutation-based test confirms no expression-level bias in the clock-target hierarchy gap.",
    file: "/figures/paper-f/Figure4_BiasAudit.png",
    type: "png",
    status: "Draft · Genome Biology",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },

  // ── Paper H — AD Glial Clock Inversion ───────────────────────────────────
  {
    id: "h-fig1",
    paper: "paper-h",
    paperLabel: "Paper H",
    figNum: "Figure 1",
    title: "Glial Clock |λ| — WT vs APP/AD Astrocytes",
    description: "Core clock and clock-target gene |λ| in WT and APP/Alzheimer's astrocytes (GSE261698). Clock genes show persistence collapse in APP condition. Pre-specified permutation test: core clock p=0.036. Also shows the Hpgd (15-PGDH) real→complex root-type shift (Δ|λ|=−0.135), consistent with Pieper & Markowitz PNAS 2026.",
    file: "/figures/paper-h/paper_h_figure1.png",
    type: "png",
    status: "Draft · Not submitted",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
    interactive: "/glial-analysis",
  },
  {
    id: "h-fig2",
    paper: "paper-h",
    paperLabel: "Paper H",
    figNum: "Figure 2",
    title: "Cell-Type Persistence Map — All Glial Subtypes",
    description: "Per-cell-type |λ| landscape across astrocytes, microglia, and oligodendrocytes in WT and APP conditions. Shows differential vulnerability of each cell type's clock programme. Astrocytes show the most pronounced clock programme disruption in APP.",
    file: "/figures/paper-h/paper_h_figure2.png",
    type: "png",
    status: "Draft · Not submitted",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
    interactive: "/glial-analysis",
  },
  {
    id: "h-figs1",
    paper: "paper-h",
    paperLabel: "Paper H",
    figNum: "Figure S1",
    title: "Core Clock Permutation Test (p=0.036)",
    description: "Pre-specified regulon permutation test for the 8-gene core clock regulon in glial data. Observed gap vs 10,000 expression-matched permutations. p=0.036 one-tailed. This was pre-specified before the APP/WT analysis was run.",
    file: "/figures/paper-h/paper_h_figure_s1.png",
    type: "png",
    status: "Draft · Not submitted",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
  },
  {
    id: "h-figs2",
    paper: "paper-h",
    paperLabel: "Paper H",
    figNum: "Figure S2",
    title: "E-box 14-Gene Permutation Test (p=0.027)",
    description: "Pre-specified regulon permutation test for the 14 direct BMAL1/CLOCK E-box target genes including Wee1, Dbp, Tef, Cdkn1a. p=0.027 two-tailed. The E-box set shows stronger signal than the core clock regulon itself in the glial context.",
    file: "/figures/paper-h/paper_h_figure_s2.png",
    type: "png",
    status: "Draft · Not submitted",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
  },

  // ── Paper M — Methods Platform (GigaScience) ──────────────────────────────
  {
    id: "m-fig1",
    paper: "paper-m",
    paperLabel: "Paper M",
    figNum: "Figure 1",
    title: "AR(2) Pipeline Architecture",
    description: "Full computational pipeline from raw time-series input to eigenvalue modulus output for the platform implementation. Shows data ingestion, quality filters, AR(2) fitting, stationarity checks, regime classification (oscillatory/real-root), and output structure.",
    file: "/figures/paper-m/Figure_1_Architecture.svg",
    type: "svg",
    status: "Draft · GigaScience",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "m-fig2",
    paper: "paper-m",
    paperLabel: "Paper M",
    figNum: "Figure 2",
    title: "Cross-Dataset Validation Summary",
    description: "Multi-species, multi-tissue validation of the clock-target |λ| hierarchy across 13+ independent datasets. Summary statistics for each dataset with effect sizes and p-values. Demonstrates reproducibility is the norm, not the exception, across the full dataset library.",
    file: "/figures/paper-m/Figure_2_Validation_Summary.svg",
    type: "svg",
    status: "Draft · GigaScience",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "m-fig3",
    paper: "paper-m",
    paperLabel: "Paper M",
    figNum: "Figure 3",
    title: "Method Comparison: AR(2) vs Cosinor vs JTK_CYCLE",
    description: "Head-to-head benchmarking of temporal persistence detection (AR(2)) versus rhythmicity detection (cosinor, JTK_CYCLE) and stability measures. Shows the orthogonality of the metrics — genes that score high on one do not preferentially score high on others.",
    file: "/figures/paper-m/Figure_3_Method_Comparison.svg",
    type: "svg",
    status: "Draft · GigaScience",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/framework-benchmarks",
  },

  // Paper N (p53 regulon) figures are withheld from the public gallery (draft / in-review).

  // ── Paper O — Organoid ───────────────────────────────────────────────────
  {
    id: "o-fig1",
    paper: "paper-o",
    paperLabel: "Paper O",
    figNum: "Figure 1",
    title: "Hierarchy Gap — Four Organoid Genotypes",
    description: "Clock-target |λ| gap for WT (+0.033), BmalKO, ApcKO (−0.127), and DblKO (+0.006) intestinal organoids (GSE157357). ApcKO inverts the hierarchy — proliferative targets now have higher persistence than clock genes. DblKO partially rescues but does not restore the WT gap.",
    file: "/figures/paper-o/Figure1_HierarchyGap_FourConditions.svg",
    type: "svg",
    status: "Draft · JBR",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/gse157357-analysis",
  },
  {
    id: "o-fig2",
    paper: "paper-o",
    paperLabel: "Paper O",
    figNum: "Figure 2",
    title: "Three-Layer Temporal Hierarchy",
    description: "Core clock genes → clock-controlled genes → E2F proliferative programme, ordered by |λ| in WT organoids. Shows both a continuous persistence gradient across the three layers and a categorical regime change from complex-root (oscillatory) to real-root (constitutive) at the E2F boundary. ApcKO E2F |λ| = 0.836.",
    file: "/figures/paper-o/Figure2_ThreeLayer_Hierarchy.svg",
    type: "svg",
    status: "Draft · JBR",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/gse157357-analysis",
  },
  {
    id: "o-figs1",
    paper: "paper-o",
    paperLabel: "Paper O",
    figNum: "Figure S1",
    title: "Gene Trajectories — WT vs ApcKO",
    description: "Individual gene expression time series for representative clock genes (Bmal1, Clock, Cry1, Per2) and E2F programme genes across WT and ApcKO organoid conditions. Shows visually why the |λ| values differ — the E2F trajectories in ApcKO are more persistent than the clock trajectories.",
    file: "/figures/paper-o/FigureS1_Gene_Trajectories.svg",
    type: "svg",
    status: "Draft · JBR",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "o-figs2",
    paper: "paper-o",
    paperLabel: "Paper O",
    figNum: "Figure S2",
    title: "Programme-Level Regulon Summary",
    description: "Regulon-level AR(2) summary showing mean |λ| ± SE for E2F, core clock, and clock-controlled gene programmes across all four organoid genotypes. ApcKO E2F mean = 0.836 is the most extreme value in the dataset. Provides the programme-level view behind the per-gene hierarchy.",
    file: "/figures/paper-o/FigureS2_Programme_Level_Regulon.svg",
    type: "svg",
    status: "Draft · JBR",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },
  {
    id: "o-figs3",
    paper: "paper-o",
    paperLabel: "Paper O",
    figNum: "Figure S3",
    title: "Algebraic Bridge — Stationarity Geometry",
    description: "The |λ| = 1/φ enrichment in the AR(2) stationarity triangle and its relationship to the algebraic bridge between AR(2) dynamics and Fibonacci-consistent growth. Shows how the condition q² = 1 − q (Boman's crypt rule) maps to a specific locus in eigenvalue space.",
    file: "/figures/paper-o/FigureS3_Algebraic_Bridge.svg",
    type: "svg",
    status: "Draft · JBR",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
  },

  // ── Paper P — Temporal Correlation Length ─────────────────────────────────
  {
    id: "p-fig1",
    paper: "paper-p",
    paperLabel: "Paper P",
    figNum: "Figure 1",
    title: "Temporal Correlation Function G(τ)",
    description: "G(τ) = |λ|^τ · cos(πτ/T₀) plotted for clock vs target genes. Shows the faster decay of the target gene correlation function and the 2× ratio in correlation length τ_c (clock 3.9h, target 2.0h). Establishes |λ| as the biological analogue of the condensed-matter correlation length.",
    file: "/figures/paper-p/Figure1_combined.png",
    type: "png",
    status: "Draft · PLOS CB",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/temporal-correlation",
  },
  {
    id: "p-fig2",
    paper: "paper-p",
    paperLabel: "Paper P",
    figNum: "Figure 2",
    title: "Tissue Validation — τ_c Ratio vs Independent Metrics",
    description: "Per-tissue clock/target τ_c ratios correlated against independent measures of circadian tissue organisation: rhythmic gene count (ρ=0.794), genome rhythmicity (ρ=0.822), gene-ratio (ρ=0.789). 13/13 tissues pass. Validates the τ_c ratio as a tissue-level property with biological meaning.",
    file: "/figures/paper-p/Figure2_combined.png",
    type: "png",
    status: "Draft · PLOS CB",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/temporal-correlation",
  },
  {
    id: "p-fig3",
    paper: "paper-p",
    paperLabel: "Paper P",
    figNum: "Figure 3",
    title: "Disease Phase Diagram",
    description: "Clock/target τ_c ratio across four biological states: Healthy 2.19×, DblKO rescue 1.22×, Bmal1-KO 0.99× (clock autonomy lost), APC-KO 0.43× (E2F programme dominant). The ratio = 1.0 boundary marks where the proliferative programme surpasses clock temporal self-organisation.",
    file: "/figures/paper-p/Figure3_regime_diagram.png",
    type: "png",
    status: "Draft · PLOS CB",
    statusColor: "bg-yellow-500/20 text-yellow-300 border-yellow-600/40",
    interactive: "/disease-screen",
  },

  // ── Paper Q — Clock Hierarchy (Nature Communications) ────────────────────
  {
    id: "q-fig1",
    paper: "paper-q",
    paperLabel: "Paper Q",
    figNum: "Panel 1",
    title: "Twelve-Tissue |λ| Gradient — SCN to Periphery",
    description: "Gallery visualization of the Paper Q core result (manuscript Fig. 1a). Mean clock gene |λ| for 16 clock genes across 12 mouse tissues (GSE54650), ordered highest to lowest. Eight peripheral tissues (lung 0.797 → skeletal muscle 0.622, mean 0.684) all rank above the three CNS tissues (brainstem 0.596, cerebellum 0.550, hypothalamus 0.469, mean 0.538). Adrenal gland (neuroendocrine, 0.682) excluded from permutation. Gap 0.146; exact C(11,3)=165 label-permutation p = 0.006; manuscript-reported bootstrap 95% CI [0.087, 0.226] (per-gene bootstrap). Pearson r = −0.95 between anatomical layer score and |λ|.",
    file: "/figures/paper-q/figure1_tissue_gradient.png",
    type: "png",
    status: "Draft · Nature Communications",
    statusColor: "bg-violet-500/20 text-violet-300 border-violet-600/40",
    interactive: "/light-entrainment",
  },
  {
    id: "q-fig2",
    paper: "paper-q",
    paperLabel: "Paper Q",
    figNum: "Panel 2",
    title: "Baboon Cross-Species Replication — 4/4 Predictions Pass",
    description: "Gallery visualization of the Paper Q baboon validation (manuscript Table 2 / Results). Pre-registered cross-species validation in baboon (GSE98965, Mure 2018). All four predictions pass: SCN ranks bottom 15% of 60 tissues (rank 9); CNS < peripheral (p = 0.006); τ_c ratio ≥ 1.3× (1.53×, live-verified; 14 stable lung genes); Spearman ρ > 0 (ρ = 0.52). Most striking: baboon SCN |λ| = 0.471 vs mouse hypothalamus |λ| = 0.469 (Δ = 0.002), indistinguishable across ~30 My of divergence.",
    file: "/figures/paper-q/figure2_cross_species.png",
    type: "png",
    status: "Draft · Nature Communications",
    statusColor: "bg-violet-500/20 text-violet-300 border-violet-600/40",
    interactive: "/light-entrainment",
  },
  {
    id: "q-figs1",
    paper: "paper-q",
    paperLabel: "Paper Q",
    figNum: "Panel S1",
    title: "Bootstrap CI & Exact Permutation Test for CNS–Peripheral Gap",
    description: "Gallery-only statistical summary (not a manuscript submission figure). Left: bootstrap distribution (n = 5,000 resamples of tissue means within each class from actual GSE54650 data) with manuscript-reported 95% CI [0.087, 0.226] shaded. Right: exact label-permutation null — all C(11,3) = 165 possible assignments of 3 CNS labels to 11 non-neuroendocrine tissues; observed gap 0.146 at the extreme right (1/165, p = 0.006). Confirms the gradient is not an artefact of small tissue sample size.",
    file: "/figures/paper-q/figure_s1_bootstrap_ci.png",
    type: "png",
    status: "Draft · Nature Communications",
    statusColor: "bg-violet-500/20 text-violet-300 border-violet-600/40",
  },

  // ── Paper U — Spaceflight Colon (npj Microgravity) ───────────────────────
  {
    id: "u-fig1",
    paper: "paper-u",
    paperLabel: "Paper U",
    figNum: "Figure 1",
    title: "Volcano Plot — Spaceflight vs Ground Control",
    description: "Differential expression volcano for 60-day ISS-exposed murine colon (GLDS-247, n=9 terminal) vs ground controls. IFN-γ response genes cluster sharply left (DOWN, p=1.5×10⁻⁹); G2M/E2F programme genes cluster right (UP, AUC=0.827, 81/106 genes UP, p=2.2×10⁻⁸). PAR bZIP genes (Dbp −1.78, Tef −1.50, Hlf −1.66 log2FC) are among the most extreme left-side points.",
    file: "/figures/paper-u/figure1_volcano.png",
    type: "png",
    status: "Draft · npj Microgravity",
    statusColor: "bg-sky-500/20 text-sky-300 border-sky-600/40",
    interactive: "/manuscript",
  },
  {
    id: "u-fig2",
    paper: "paper-u",
    paperLabel: "Paper U",
    figNum: "Figure 2",
    title: "14-Gene Circadian Heatmap — Flight vs Ground vs LAR",
    description: "Row-normalised heatmap of 14 circadian clock genes across three conditions: terminal flight (n=9), ground control (n=9), and live-animal-return/LAR arm (n=6, 4 days post-landing). Shows PAR bZIP depletion (Dbp, Tef, Hlf) and activator/repressor uncoupling in flight, with complete reversal in LAR. The reversal row confirms re-entrainment restores the clock programme.",
    file: "/figures/paper-u/figure2_heatmap.png",
    type: "png",
    status: "Draft · npj Microgravity",
    statusColor: "bg-sky-500/20 text-sky-300 border-sky-600/40",
  },
  {
    id: "u-fig3",
    paper: "paper-u",
    paperLabel: "Paper U",
    figNum: "Figure 3",
    title: "TTFL Clock Schematic — PAR bZIP Output Gate",
    description: "Schematic of the transcription-translation feedback loop (TTFL) in the spaceflight colon. BMAL1/NPAS2 activators (UP in flight) drive E-box targets but the PAR bZIP output arm (Dbp, Tef, Hlf) is paradoxically silenced, indicating post-transcriptional uncoupling or a secondary suppression mechanism. Wee1 sits at the G2M gate; its reduction (−0.91 log2FC) removes the circadian brake on cell division. Arrows indicate direction of change vs ground controls.",
    file: "/figures/paper-u/figure3_clock_schematic.png",
    type: "png",
    status: "Draft · npj Microgravity",
    statusColor: "bg-sky-500/20 text-sky-300 border-sky-600/40",
    interactive: "/manuscript",
  },

  // ── Platform Visualizations ──────────────────────────────────────────────
  {
    id: "platform-rootspace",
    paper: "platform",
    paperLabel: "Platform",
    figNum: "Viz 1",
    title: "AR(2) Root-Space Geometry",
    description: "Unit circle plot showing the distribution of AR(2) eigenvalues (real and complex) across all analysed clock and target genes. Complex roots appear as pairs inside the unit circle. The stationarity triangle defines the boundary between stable AR(2) dynamics and explosive/non-stationary processes.",
    file: "/figures/platform/ar2_viz2_rootspace.png",
    type: "png",
    status: "Platform",
    statusColor: "bg-blue-500/20 text-blue-300 border-blue-600/40",
    interactive: "/root-space",
  },
  {
    id: "platform-period",
    paper: "platform",
    paperLabel: "Platform",
    figNum: "Viz 2",
    title: "Period vs Persistence Scatter",
    description: "AR(2) oscillation period (derived from eigenvalue argument angle) plotted against eigenvalue modulus |λ| for all analysed genes. Shows the two-dimensional distribution of biological oscillators. Clock genes cluster near the 24h period with higher |λ|; target genes are dispersed.",
    file: "/figures/platform/ar2_viz3_period_persistence.png",
    type: "png",
    status: "Platform",
    statusColor: "bg-blue-500/20 text-blue-300 border-blue-600/40",
    interactive: "/root-space",
  },
  {
    id: "platform-violin",
    paper: "platform",
    paperLabel: "Platform",
    figNum: "Viz 3",
    title: "Tissue |λ| Violin Plot",
    description: "Distribution of eigenvalue moduli across 12 mouse tissues (GSE54650), showing clock and target gene tiers as overlapping violins per tissue. The consistent separation between clock and target distributions in every tissue is the foundational observation of the entire platform.",
    file: "/figures/platform/ar2_viz4_tissue_violin.png",
    type: "png",
    status: "Platform",
    statusColor: "bg-blue-500/20 text-blue-300 border-blue-600/40",
    interactive: "/dashboard",
  },
  {
    id: "platform-density",
    paper: "platform",
    paperLabel: "Platform",
    figNum: "Viz 4",
    title: "AR(2) Parameter Density (φ₁, φ₂ Space)",
    description: "Joint density of AR(2) coefficients φ₁ and φ₂ across the full gene expression dataset. The stationarity triangle boundary is overlaid. Clock genes and target genes occupy different sub-regions of the stable parameter space, reflecting both their persistence and oscillatory properties.",
    file: "/figures/platform/ar2_parameter_density.png",
    type: "png",
    status: "Platform",
    statusColor: "bg-blue-500/20 text-blue-300 border-blue-600/40",
    interactive: "/root-space",
  },

  // ── Manuscript Supplementary Figures ────────────────────────────────────
  {
    id: "ms-fig1",
    paper: "manuscripts",
    paperLabel: "Supplementary",
    figNum: "Supp 1",
    title: "Discovery Rates — AR(2) vs Alternatives",
    description: "Bar chart comparing the number of validated circadian biology findings recovered by AR(2) vs alternative methods across the full dataset library. Shows the hit rate for known clock genes, published regulons, and disease-state differences.",
    file: "/figures/manuscripts/figure1_discovery_rates.png",
    type: "png",
    status: "Platform supplement",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
  },
  {
    id: "ms-fig2",
    paper: "manuscripts",
    paperLabel: "Supplementary",
    figNum: "Supp 2",
    title: "Eigenvalue Heatmap — Genes × Tissues",
    description: "Heatmap of per-gene |λ| values across all 12 mouse tissues, with genes ordered by mean |λ|. Clock gene cluster at the top; background genes at the bottom. Shows the cross-tissue consistency of the eigenvalue hierarchy and identifies the genes with tissue-specific versus ubiquitous persistence.",
    file: "/figures/manuscripts/figure2_heatmap.png",
    type: "png",
    status: "Platform supplement",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
    interactive: "/genome-wide",
  },
  {
    id: "ms-fig3",
    paper: "manuscripts",
    paperLabel: "Supplementary",
    figNum: "Supp 3",
    title: "Pathway Model Schematic",
    description: "Schematic of the circadian-cell cycle pathway linkage as modelled by the AR(2) framework. Shows the clock feedback loop, E-box transcription of target genes, and how eigenvalue modulus maps onto the dynamical properties of each layer.",
    file: "/figures/manuscripts/figure3_model.png",
    type: "png",
    status: "Platform supplement",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
  },
  {
    id: "ms-fig4",
    paper: "manuscripts",
    paperLabel: "Supplementary",
    figNum: "Supp 4",
    title: "Wee1 Eigenvalue Profile Across 12 Tissues",
    description: "Per-tissue |λ| for Wee1 (the G2/M checkpoint kinase and direct CLOCK:BMAL1 E-box target). In GSE54650 liver, Wee1 has |λ|=0.615 — within 0.003 of 1/φ≈0.618, among the nearest values in the liver dataset. Values vary by tissue (heart 0.671, kidney 0.635). Consistent with Wee1 as a temporally persistent gatekeeper of crypt cell division.",
    file: "/figures/manuscripts/figure4_wee1_profile.png",
    type: "png",
    status: "Platform supplement",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
    interactive: "/gene-explorer",
  },
  {
    id: "ms-fig5",
    paper: "manuscripts",
    paperLabel: "Supplementary",
    figNum: "Supp 5",
    title: "Cross-Dataset Validation Summary",
    description: "Summary validation figure showing the clock-target |λ| hierarchy replicated across the full dataset library. Each dataset is a point — effect size on one axis, significance on the other. Shows consistent, reproducible separation across the library.",
    file: "/figures/manuscripts/figure5_validation.png",
    type: "png",
    status: "Platform supplement",
    statusColor: "bg-gray-500/20 text-gray-300 border-gray-600/40",
    interactive: "/convergence-map",
  },
];

const PAPERS = [
  { id: "all", label: "All" },
  { id: "paper-a", label: "Paper A — Core Methods" },
  { id: "paper-e", label: "Paper E — Phase-Gated" },
  { id: "paper-f", label: "Paper F — Half-Life" },
  { id: "paper-h", label: "Paper H — AD Glial" },
  { id: "paper-m", label: "Paper M — Methods" },
  { id: "paper-o", label: "Paper O — Organoid" },
  { id: "paper-p", label: "Paper P — Temporal Corr." },
  { id: "paper-q", label: "Paper Q — Clock Hierarchy" },
  { id: "paper-u", label: "Paper U — Spaceflight Colon" },
  { id: "platform", label: "Platform" },
  { id: "manuscripts", label: "Supplementary" },
];

function FigureCard({ fig, onClick }: { fig: Figure; onClick: () => void }) {
  const [imgError, setImgError] = useState(false);
  const handleError = useCallback(() => setImgError(true), []);

  return (
    <div
      className="bg-gray-900 border border-gray-700 rounded-xl overflow-hidden hover:border-gray-500 transition-colors cursor-pointer group"
      onClick={onClick}
      data-testid={`figure-card-${fig.id}`}
    >
      <div className="bg-gray-800 h-44 flex items-center justify-center overflow-hidden relative">
        {imgError ? (
          <div className="flex flex-col items-center justify-center gap-2 text-center p-4 select-none">
            <svg className="w-9 h-9 text-gray-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <rect x="3" y="3" width="18" height="18" rx="2" />
              <path d="M3 9h18M9 21V9" />
              <circle cx="16" cy="15" r="1.5" fill="currentColor" stroke="none" />
              <path d="M6 15l3-3 2 2" />
            </svg>
            <div>
              <p className="text-gray-400 text-xs font-medium">{fig.paperLabel} · {fig.figNum}</p>
              <p className="text-gray-600 text-xs mt-0.5">Not yet rendered</p>
            </div>
          </div>
        ) : (
          <img
            src={fig.file}
            alt={fig.title}
            className="max-h-full max-w-full object-contain p-2"
            loading="lazy"
            onError={handleError}
          />
        )}
        {!imgError && (
          <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
            <a
              href={fig.file}
              download
              onClick={(e) => e.stopPropagation()}
              className="bg-gray-900/90 text-white text-xs px-2 py-1 rounded border border-gray-600 hover:bg-gray-700"
              data-testid={`download-${fig.id}`}
            >
              ↓ Download
            </a>
          </div>
        )}
      </div>
      <div className="p-4">
        <div className="flex items-center gap-2 mb-1 flex-wrap">
          <span className="text-xs font-semibold text-emerald-400">{fig.paperLabel}</span>
          <span className="text-xs text-gray-500">·</span>
          <span className="text-xs text-gray-400">{fig.figNum}</span>
          <span className={`ml-auto text-xs px-2 py-0.5 rounded border font-medium ${fig.statusColor}`}>
            {fig.type.toUpperCase()}
          </span>
        </div>
        <h3 className="text-sm font-semibold text-white mb-1 leading-snug">{fig.title}</h3>
        <p className="text-xs text-gray-400 leading-relaxed line-clamp-3">{fig.description}</p>
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <span className={`text-xs px-2 py-0.5 rounded border ${fig.statusColor}`}>{fig.status}</span>
          {fig.interactive && (
            <a
              href={fig.interactive}
              onClick={(e) => e.stopPropagation()}
              className="text-xs text-purple-400 hover:text-purple-300 underline"
            >
              Interactive →
            </a>
          )}
        </div>
      </div>
    </div>
  );
}

function LightboxModal({ fig, onClose }: { fig: Figure; onClose: () => void }) {
  return (
    <div
      className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4"
      onClick={onClose}
      data-testid="lightbox-overlay"
    >
      <div
        className="bg-gray-900 border border-gray-700 rounded-xl max-w-5xl w-full max-h-[92vh] overflow-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between p-4 border-b border-gray-700 gap-4">
          <div className="min-w-0">
            <div className="flex items-center gap-2 mb-1 flex-wrap">
              <span className="text-sm font-semibold text-emerald-400">{fig.paperLabel}</span>
              <span className="text-gray-500">·</span>
              <span className="text-sm text-gray-400">{fig.figNum}</span>
              <span className={`text-xs px-2 py-0.5 rounded border ${fig.statusColor}`}>{fig.status}</span>
            </div>
            <h2 className="text-lg font-bold text-white leading-snug">{fig.title}</h2>
          </div>
          <div className="flex gap-2 items-center flex-shrink-0">
            <a
              href={fig.file}
              download
              className="text-sm bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1.5 rounded-lg font-medium whitespace-nowrap"
              data-testid="lightbox-download"
            >
              ↓ {fig.type.toUpperCase()}
            </a>
            {fig.interactive && (
              <a
                href={fig.interactive}
                className="text-sm bg-purple-600 hover:bg-purple-700 text-white px-3 py-1.5 rounded-lg font-medium whitespace-nowrap"
              >
                Interactive →
              </a>
            )}
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-white text-2xl leading-none px-2"
              data-testid="lightbox-close"
            >
              ×
            </button>
          </div>
        </div>
        <div className="p-4 flex items-center justify-center bg-gray-950 min-h-72">
          <img
            src={fig.file}
            alt={fig.title}
            className="max-w-full max-h-[60vh] object-contain"
          />
        </div>
        <div className="p-4 border-t border-gray-700">
          <p className="text-sm text-gray-300 leading-relaxed">{fig.description}</p>
        </div>
      </div>
    </div>
  );
}

export default function FiguresGallery() {
  const [filter, setFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [lightbox, setLightbox] = useState<Figure | null>(null);

  const visible = FIGURES.filter((f) => {
    const matchPaper = filter === "all" || f.paper === filter;
    const q = search.toLowerCase();
    const matchSearch =
      q === "" ||
      f.title.toLowerCase().includes(q) ||
      f.description.toLowerCase().includes(q) ||
      f.paperLabel.toLowerCase().includes(q) ||
      f.figNum.toLowerCase().includes(q);
    return matchPaper && matchSearch;
  });

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      {lightbox && <LightboxModal fig={lightbox} onClose={() => setLightbox(null)} />}
      <div className="max-w-7xl mx-auto px-4 py-8">

        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-2 h-8 bg-emerald-500 rounded-full" />
            <h1 className="text-3xl font-bold text-white">Figures Gallery</h1>
          </div>
          <p className="text-gray-400 ml-5 text-lg">
            All {FIGURES.length} figures, diagrams, and visualizations across all PAR(2) papers — view and download
          </p>
        </div>

        <div className="flex flex-col sm:flex-row gap-3 mb-5">
          <input
            type="text"
            placeholder="Search by title, description, gene name…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="bg-gray-800 border border-gray-700 text-white placeholder-gray-500 rounded-lg px-4 py-2 text-sm flex-1 focus:outline-none focus:border-emerald-500"
            data-testid="input-search-figures"
          />
          <a
            href="/figures/all-figures.zip"
            download
            className="bg-emerald-600 hover:bg-emerald-700 text-white text-sm px-4 py-2 rounded-lg font-medium whitespace-nowrap flex items-center gap-1"
            data-testid="link-download-all"
          >
            ↓ Download All ({FIGURES.length} files)
          </a>
        </div>

        <div className="flex flex-wrap gap-2 mb-5">
          {PAPERS.map((p) => {
            const count = p.id === "all" ? FIGURES.length : FIGURES.filter((f) => f.paper === p.id).length;
            return (
              <button
                key={p.id}
                onClick={() => setFilter(p.id)}
                data-testid={`filter-${p.id}`}
                className={`text-xs px-3 py-1.5 rounded-full border font-medium transition-colors ${
                  filter === p.id
                    ? "bg-emerald-600 border-emerald-500 text-white"
                    : "bg-gray-800 border-gray-700 text-gray-400 hover:border-gray-500 hover:text-gray-200"
                }`}
              >
                {p.label} <span className="opacity-60">({count})</span>
              </button>
            );
          })}
        </div>

        <p className="text-sm text-gray-500 mb-4">
          Showing {visible.length} of {FIGURES.length} figures
        </p>

        {visible.length === 0 ? (
          <div className="text-center py-16 text-gray-500">No figures match your search.</div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
            {visible.map((fig) => (
              <FigureCard key={fig.id} fig={fig} onClick={() => setLightbox(fig)} />
            ))}
          </div>
        )}

        <div className="mt-10 pt-6 border-t border-gray-800 text-xs text-gray-500 flex flex-wrap gap-4">
          <span>Click any card to preview full-size with description.</span>
          <span>Hover a card to reveal the quick download button.</span>
          <span>Interactive links open the live analysis page for that figure.</span>
        </div>
      </div>
    </div>
  );
}
