/**
 * Export per-gene, per-tissue Floquet coefficient pairs to JSON.
 * Used by manuscripts/figures/stationarity_triangle_figure.py to plot actual
 * fitted day-gate and night-gate AR(2) coefficients (φ₁, φ₂) in Figure 1.
 *
 * Usage:  npx tsx scripts/export_floquet_coefficients.ts
 * Output: manuscripts/figures/floquet_coefficients.json
 */

import * as fs from 'fs';
import { runFloquetAnalysis } from '../server/floquet-analysis';

const report = runFloquetAnalysis();

// Collect every gene–tissue result that has actual fitted coefficients.
// We include both Direct BMAL1/CLOCK E-box targets and core clock genes.
const allResults = [...report.genes, ...report.coreClockGenes];

interface CoeffEntry {
  gene: string;
  tier: string;
  tissue: string;
  phi1_day: number;
  phi2_day: number;
  phi1_night: number;
  phi2_night: number;
  dayEigenvalue: number;
  nightEigenvalue: number;
  isStable: boolean;
  transientFibonacci: boolean;
}

const entries: CoeffEntry[] = [];

for (const geneResult of allResults) {
  for (const tr of geneResult.tissueResults) {
    entries.push({
      gene: geneResult.gene,
      tier: geneResult.tier,
      tissue: tr.tissue,
      phi1_day: tr.phi1_day,
      phi2_day: tr.phi2_day,
      phi1_night: tr.phi1_night,
      phi2_night: tr.phi2_night,
      dayEigenvalue: tr.dayEigenvalue,
      nightEigenvalue: tr.nightEigenvalue,
      isStable: tr.isStable,
      transientFibonacci: tr.transientFibonacci,
    });
  }
}

const output = {
  description: 'Per-gene, per-tissue Floquet AR(2) day/night coefficient pairs from GSE54650. ' +
    'Generated by scripts/export_floquet_coefficients.ts. ' +
    'Used by manuscripts/figures/stationarity_triangle_figure.py (Figure 1).',
  generated: new Date().toISOString(),
  nEntries: entries.length,
  entries,
};

const outPath = 'manuscripts/figures/floquet_coefficients.json';
fs.writeFileSync(outPath, JSON.stringify(output, null, 2));
console.log(`Written ${entries.length} gene–tissue coefficient pairs to ${outPath}`);
