import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ReportSection {
  heading: string;
  content: string | { type: 'table'; headers: string[]; rows: string[][] } | { type: 'stats'; items: { label: string; value: string | number }[] };
}

interface ExportReportProps {
  title: string;
  subtitle?: string;
  sections: ReportSection[];
  className?: string;
}

function renderSection(section: ReportSection): string {
  let contentHTML = '';

  if (typeof section.content === 'string') {
    contentHTML = `<p>${section.content}</p>`;
  } else if (section.content.type === 'table') {
    const headerRow = section.content.headers.map(h => `<th>${h}</th>`).join('');
    const bodyRows = section.content.rows.map(row =>
      `<tr>${row.map(cell => `<td>${cell}</td>`).join('')}</tr>`
    ).join('');
    contentHTML = `<table><thead><tr>${headerRow}</tr></thead><tbody>${bodyRows}</tbody></table>`;
  } else if (section.content.type === 'stats') {
    const cards = section.content.items.map(item =>
      `<div class="stat-card"><div class="stat-value">${item.value}</div><div class="stat-label">${item.label}</div></div>`
    ).join('');
    contentHTML = `<div class="stats-grid">${cards}</div>`;
  }

  return `<h2>${section.heading}</h2>${contentHTML}`;
}

function generateHTML(title: string, subtitle: string | undefined, sections: ReportSection[]): string {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>
body { font-family: -apple-system, system-ui, sans-serif; background: #0f172a; color: #e2e8f0; max-width: 900px; margin: 0 auto; padding: 40px 20px; }
h1 { color: #22d3ee; border-bottom: 2px solid #1e293b; padding-bottom: 12px; }
h2 { color: #94a3b8; margin-top: 30px; }
table { width: 100%; border-collapse: collapse; margin: 16px 0; }
th { background: #1e293b; color: #22d3ee; padding: 10px; text-align: left; border: 1px solid #334155; }
td { padding: 8px 10px; border: 1px solid #334155; }
tr:nth-child(even) { background: #1e293b40; }
.stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin: 16px 0; }
.stat-card { background: #1e293b; border-radius: 8px; padding: 16px; text-align: center; }
.stat-value { font-size: 24px; font-weight: bold; color: #22d3ee; }
.stat-label { font-size: 12px; color: #94a3b8; margin-top: 4px; }
.footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #334155; color: #94a3b8; font-size: 12px; }
@media print { body { background: white; color: black; } h1 { color: #0891b2; } th { background: #f1f5f9; color: #0891b2; } .stat-label { color: #475569; } .footer { color: #475569; border-color: #e2e8f0; } }
</style></head><body>
<h1>${title}</h1>
${subtitle ? `<p style="color:#94a3b8">${subtitle}</p>` : ''}
${sections.map(renderSection).join('')}
<div class="footer">Generated by PAR(2) Discovery Engine on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
</body></html>`;
}

export default function ExportReport({ title, subtitle, sections, className }: ExportReportProps) {
  const handleDownload = () => {
    const html = generateHTML(title, subtitle, sections);
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    const dateStr = new Date().toISOString().split('T')[0];
    const safeTitle = title.replace(/[^a-zA-Z0-9]/g, '_');
    link.href = url;
    link.download = `PAR2_Report_${safeTitle}_${dateStr}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleDownload}
      className={className}
      data-testid="button-export-report"
    >
      <Download className="mr-2 h-4 w-4" />
      Download Report
    </Button>
  );
}
